services:
    mongo:
        container_name: k-db-1
        image: mongo
        restart: always
        ports:
            - 27017:27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: 123

    # mongo-express:
    #     container_name: k-dbui-1
    #     image: mongo-express
    #     restart: always
    #     ports:
    #         - 8081:8081
    #     environment:
    #         ME_CONFIG_MONGODB_SERVER: mongo
    #         ME_CONFIG_MONGODB_PORT: 27017
    #         ME_CONFIG_MONGODB_ADMINUSERNAME: root
    #         ME_CONFIG_MONGODB_ADMINPASSWORD: 123
    #         ME_CONFIG_MONGODB_URL: mongodb://root:123@k-db-1:27017/
    #         ME_CONFIG_BASICAUTH: false
